"""Arkham TSV エクスポートから取引所カウンターパーティ候補を抽出し、labels.yaml 断片を出力。

OFFLINE 専用ツール。出力を必ず人がレビューしてから config/labels.yaml に追記すること
(自動転載しない=ToSクリーンの担保)。Bot 実行時はこのスクリプトを呼ばない。

使い方:
    uv run python scripts/build_labels.py scripts/blackrock_arkham.tsv [more.tsv ...]
    uv run python scripts/build_labels.py scripts/*.tsv > /tmp/labels_fragment.yaml

TSV列(Arkham): transactionHash, fromAddress, fromLabel, ..., toAddress, toLabel, ..., chain
fromAddress はカンマ区切りで複数入ることがある(fromLabel は代表+「(+N)」表記)。
"""
from __future__ import annotations

import csv
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.config import load_clusters  # noqa: E402

# ラベル文字列 -> 正規化エンティティ名(既知の取引所/カストディのみ。誤抽出防止に allowlist)。
KEYWORDS: dict[str, str] = {
    "coinbase": "Coinbase",
    "binance": "Binance",
    "kraken": "Kraken",
    "bitfinex": "Bitfinex",
    "okx": "OKX",
    "okex": "OKX",
    "bybit": "Bybit",
    "gemini": "Gemini",
    "kucoin": "KuCoin",
    "robinhood": "Robinhood",
    "bitstamp": "Bitstamp",
    "galaxy": "Galaxy Digital",
    "cumberland": "Cumberland",
}


def entity_for(label: str) -> str | None:
    low = (label or "").lower()
    for kw, name in KEYWORDS.items():
        if kw in low:
            return name
    return None


def main(paths: list[str]) -> None:
    clusters = load_clusters()
    our_btc = {a for c in clusters.btc_clusters for a in c.addresses}
    our_eth = {a.lower() for c in clusters.eth_clusters for a in c.addresses}

    # (entity, chain) -> set(address)
    found: dict[tuple[str, str], set[str]] = {}

    for p in paths:
        with open(p, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                chain = (row.get("chain") or "").strip().lower()
                if chain not in ("bitcoin", "ethereum"):
                    continue
                for addr_col, label_col in (("fromAddress", "fromLabel"), ("toAddress", "toLabel")):
                    ent = entity_for(row.get(label_col, ""))
                    if not ent:
                        continue
                    raw = (row.get(addr_col) or "").strip().strip('"')
                    for a in raw.split(","):
                        a = a.strip()
                        if not a:
                            continue
                        norm = a.lower() if chain == "ethereum" else a
                        if (chain == "bitcoin" and a in our_btc) or (chain == "ethereum" and norm in our_eth):
                            continue  # 自前ETFは labels.yaml に入れない(clusters.yaml が優先)
                        found.setdefault((ent, chain), set()).add(a)

    if not found:
        print("# (no exchange-labeled counterparties found)", file=sys.stderr)
        return

    today = date.today().isoformat()
    print("# --- labels.yaml fragment (REVIEW before pasting into config/labels.yaml) ---")
    print("# generated by scripts/build_labels.py ; verify each address is current.")
    for (ent, chain), addrs in sorted(found.items()):
        print(f"  - name: {ent}")
        print("    type: exchange")
        print(f"    chain: {chain}")
        print(f'    as_of: "{today}"')
        print("    addresses:")
        for a in sorted(addrs):
            q = f"'{a}'" if chain == "ethereum" else a
            print(f"      - {q}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    main(sys.argv[1:])
